# Generated by Django 5.0 on 2023-12-16 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_token'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='owner',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
            preserve_default=False,
        ),
    ]
