# Generated by Django 5.0 on 2023-12-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_wallet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
    ]
