# Generated by Django 5.0 on 2024-01-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_pay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='password',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
